### ISSUE TITLE
Why using shell insead of eshell?

### ISSUE THREAD

**Issue by maximvl** [killdash9/better-shell#3]
Hi, is there any point of using regular shell instead of integrated eshell? Why not improve the second one which tries to bring emacs features to shell, instead of just redirecting the output?

**Comment by killdash9** [comment]
I use shell way more than I use eshell, which is why better-shell uses shell.  But perhaps I should give eshell another look.

**Comment by killdash9** [comment]
I don't plan to add eshell support.  Closing this issue.
