### ISSUE TITLE
"cd /scp:host:/foo/bar": No such file or directory

### ISSUE THREAD

**Issue by pmiddend** [killdash9/better-shell#4]
First of all, thanks for a plugin that is really, really handy in my day-to-day emacs usage!

Now, I've created a useful keybinding

```
(global-set-key (kbd "C-'") (lambda () (interactive) (better-shell-shell 4)))
```

To invoke a shell for the file I am currently visiting. I'd like it to reuse an existing shell if possible, otherwise open a new one. This works locally, but not remotely. If I have a shell open in `/scp:host:/path` and I invoke the above command when I'm visiting `/scp:host:/path/dir/file`, I get:

```
bash: cd: /scp:host:/path/dir: No such file or directory
```

Is that a configuration issue on my side, or can it be fixed? It doesn't work with `ssh:` either, by the way.

**Comment by killdash9** [comment]
I've fixed both the "No such file or directory" bug and the not working with ssh bug.  I'll test it out locally for a couple weeks and then push it out.  Thanks for reporting it and sorry it has taken so long.
