### ISSUE TITLE
Cycles only between two shells

### ISSUE THREAD

**Issue by noorul** [killdash9/better-shell#6]
I have four shells open, but better-shell-shell only cycles through two of them. Is this the desired behaviour?

**Comment by killdash9** [comment]
It should cycle through all of them.  Do you have the latest version?  The list of shells it will cycle through is retrieved with the `better-shell-shells` function.  When you run 

    M-: (better-shell-shells) 

Do you see all of your shells?

**Comment by noorul** [comment]
It returned (#<buffer *shell*> #<buffer *shell*<3>> #<buffer *shell*<2>>)

**Comment by noorul** [comment]
It cycles between last visited two buffers.

**Comment by noorul** [comment]
From the .el header

;; Author: Russell Black (killdash9@github)
;; Keywords: convenience
;; Package-Version: 20170205.2308
;; URL: https://github.com/killdash9/better-shell
;; Created: 1st Mar 2016
;; Version: 1.1
;; Package-Requires: ((emacs "24.4"))

**Comment by noorul** [comment]
@killdash9 Do you think this is a bug?

**Comment by killdash9** [comment]
It does sound like a bug, but I'm not able to reproduce this problem.  If you can give me reliable steps to reproduce the problem with a bare-bones emacs (emacs -q), I will fix it.

**Comment by alastairdb** [comment]
The problem is that `better-shell-shells` is dynamic. So you are cycling through a different list on each invocation of `better-shell-shell`. Something like the following would fix it:
``` elisp
(defvar better-shell-last-shells nil)

(defun better-shell-shells ()
  "Return a list of buffers running shells."
  (if (or (eq last-command 'better-shell-shell)
	  (eq last-command 'better-shell-existing-shell))
      better-shell-last-shells
    (setq better-shell-last-shells
	  (cl-remove-if-not
	   (lambda (buf)
	     (and
	      (get-buffer-process buf)
	      (with-current-buffer buf
		(string-equal major-mode 'shell-mode))))
	   (buffer-list)))))
```

**Comment by killdash9** [comment]
@alastairdb, Thanks for suggesting that solution.  Actually, the logic to prevent getting a different list each time happens in `better-shell-existing-shell`.  It happens by virtue of the fact that the first switch-to-buffer call in that function switches to the buffer without reordering the "stack" returned by `(buffer-list)`.  This is achieved with the NORECORD parameter on` switch-to-buffer`.  Once a keystroke is typed which is different from the one one used to invoke the command, the current buffer is placed on top of the (buffer-list) stack with the second call to `switch-to-buffer` without NORECORD.  

@noorul, what key do you have bound to `better-shell-shell`

**Comment by killdash9** [comment]
@noorul Is this still happening?  I will close this ticket if I don't hear back from you.

**Comment by noorul** [comment]
Closing this, as I am not using it anymore
