### ISSUE TITLE
Please provide config option to use ansi-term rather than shell

### ISSUE THREAD

**Issue by PhilipDaniels** [killdash9/better-shell#7]
Was happy to find this package, it is similar (but more powerful) to some functions I had written for myself to deal with ansi-term buffers.

However, I have a request: would it be possible to add a configuration option to provide the same functionality over ansi-term rather than shell? I have some minor tweaks that look at term-exec-hook, which term and ansi-term run, but shell mode doesn't. For example, to automatically close the buffer when you type "exit" in the shell, from here http://oremacs.com/2015/01/01/three-ansi-term-tips/

**Comment by PhilipDaniels** [comment]
Found another reason to prefer a version that works with ansi-term: some git commands in shell mode complain about the terminal not being fully functional. No such problems in ansi-term.

**Comment by killdash9** [comment]
Ansi term support is not high on my priority list.  I've tried unsuccessfully multiple times to integrate it into my work flow and I personally find it cumbersome.  

However I think ansi-term support is a good suggestion that that many others would like.  I would welcome a pull request on this if you would like to add ansi-term support.

**Comment by PhilipDaniels** [comment]
I took quite a long look at this and unfortunately it is harder than I expected. Although it is fairly easy to refactor parts of better shell so that they switch from shell-mode to term-mode, that is only half the story. shell provides facilities such as directory tracking and tramp integration that term does not. shell-mode is derived from comint-mode, while term-mode is not. It is a pity that shell mode is not more fully functional, there really ought to be a merge of the two modes' capabilities. Alas, that is beyond me. So I think this one has to go to bed.
